# Generated by matugen, do not edit
export THEME_USER="#bdc2ff"
export THEME_PATH="#e7b9d6"
export THEME_SYMBOL="#e4e1e9"

export FZF_DEFAULT_OPTS="
    --style=full
    --color=fg:#e4e1e9,fg+:#c7c5d0
    --color=hl:#bdc2ff,hl+:#dfe0ff
    --color=border:#46464f
    --color=header:#e0e0f9
    --color=gutter:#131318
    --color=spinner:#e7b9d6,info:#ffd7ef
    --color=pointer:#dfe0ff,marker:#ffb4ab
    --color=prompt:#c7c5d0,query:#e4e1e9
    --color=preview-fg:#e4e1e9,preview-bg:-1
    --height=50%
    --layout=reverse
    --border
"
