# Generated by matugen, do not edit
export THEME_USER="{{colors.primary.default.hex}}"
export THEME_PATH="{{colors.tertiary.default.hex}}"
export THEME_SYMBOL="{{colors.on_surface.default.hex}}"

export FZF_DEFAULT_OPTS="
    --style=full
    --color=fg:{{colors.on_surface.default.hex}},fg+:{{colors.on_surface_variant.default.hex}}
    --color=hl:{{colors.primary.default.hex}},hl+:{{colors.on_primary_container.default.hex}}
    --color=border:{{colors.outline_variant.default.hex}}
    --color=header:{{colors.on_secondary_container.default.hex}}
    --color=gutter:{{colors.surface.default.hex}}
    --color=spinner:{{colors.tertiary.default.hex}},info:{{colors.on_tertiary_container.default.hex}}
    --color=pointer:{{colors.primary_fixed.default.hex}},marker:{{colors.error.default.hex}}
    --color=prompt:{{colors.on_surface_variant.default.hex}},query:{{colors.on_surface.default.hex}}
    --color=preview-fg:{{colors.on_surface.default.hex}},preview-bg:-1
    --height=50%
    --layout=reverse
    --border
"
