#!/usr/bin/env bash

set -euo pipefail
# Don't react on USR1, as it is used by matugen to signal zsh to reload color theme.
trap '' USR1

update_sddm=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        -s|--sddm)
            update_sddm=true
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [--sddm] /path/to/image"
            exit 0
            ;;
        *)
            img_arg="$1"
            shift
            ;;
    esac
done

for cmd in ffmpeg matugen hyprctl; do
    command -v "$cmd" >/dev/null || { echo "$cmd missing"; exit 1; }
done

if [[ -z "${img_arg:-}" ]]; then
    echo "usage: $0 [--sddm] /path/to/image" >&2
    exit 1
fi

img_path="$(realpath "$img_arg")"

if [[ ! -f "$img_path" ]]; then
    echo "error: file does not exist -> $img_path"
    exit 1
fi
if ! file --mime-type -b "$img_path" | grep -q '^image/'; then
    echo "error: not a valid image"
    exit 1
fi

: "${XDG_CACHE_HOME:=$HOME/.cache}"
cache_dir="$XDG_CACHE_HOME/arch-rice/wallpaper"
mkdir -p "$cache_dir"

if [[ -f "$cache_dir/current.txt" && "$(<"$cache_dir/current.txt")" == "$img_path" ]]; then
    echo "Wallpaper already active."
    exit 0
fi

echo "$img_path" > "$cache_dir/current.txt"

img_ext="${img_path##*.}"
img_ext="${img_ext,,}"

ln -sf "$img_path" "$cache_dir/current"

img_hash=$(sha1sum "$img_path" | cut -d' ' -f1)
img_blurred="$cache_dir/$img_hash.$img_ext"

# generate only if missing
if [[ ! -f "$img_blurred" ]]; then
    ffmpeg -v error -y -i "$img_path" \
        -vf "scale=iw/2:ih/2,gblur=sigma=15,gblur=sigma=15,gblur=sigma=15" \
        "$img_blurred"
fi

ln -sf "$img_blurred" "$cache_dir/current_blurred"

current_ws=$(hyprctl activeworkspace -j 2>/dev/null | grep -oP 'id": *\K[^,]*')

# turn off monitor after the script if disabled, as matugen calls hyprctl reload
builtin_off=false
if ! hyprctl monitors -j 2>/dev/null | grep -q '"name": *"eDP-1"'; then
    builtin_off=true
fi

matugen --quiet image "$img_path" --mode dark

sleep 0.25

hyprctl hyprpaper wallpaper ",$cache_dir/current"

sleep 0.25

if [[ "$builtin_off" == true ]]; then
    hyprctl keyword monitor "eDP-1,disable" &>/dev/null
fi

sleep 0.25

hyprctl dispatch workspace "$current_ws" &>/dev/null

if [[ "$update_sddm" == true ]]; then
    echo "Updating SDDM background..."
    sudo -v || exit 1
    sudo install -Dm0644 \
        "$img_path" \
        "/usr/share/sddm/themes/sequoia/backgrounds/current_wallpaper"
else
    echo "Skipping SDDM background update."
fi
