# Generated by matugen, do not edit
#
export THEME_USER="#9ecafc"
export THEME_PATH="#d5bee5"
export THEME_SYMBOL="#e1e2e8"


export theme_background="#101418"

export theme_error="#ffb4ab"

export theme_error_container="#93000a"

export theme_inverse_on_surface="#2d3135"

export theme_inverse_primary="#34618d"

export theme_inverse_surface="#e1e2e8"

export theme_on_background="#e1e2e8"

export theme_on_error="#690005"

export theme_on_error_container="#ffdad6"

export theme_on_primary="#003256"

export theme_on_primary_container="#d0e4ff"

export theme_on_primary_fixed="#001d35"

export theme_on_primary_fixed_variant="#164974"

export theme_on_secondary="#243140"

export theme_on_secondary_container="#d6e4f7"

export theme_on_secondary_fixed="#0f1d2a"

export theme_on_secondary_fixed_variant="#3b4857"

export theme_on_surface="#e1e2e8"

export theme_on_surface_variant="#c2c7cf"

export theme_on_tertiary="#3a2948"

export theme_on_tertiary_container="#f1daff"

export theme_on_tertiary_fixed="#241432"

export theme_on_tertiary_fixed_variant="#514060"

export theme_outline="#8c9199"

export theme_outline_variant="#42474e"

export theme_primary="#9ecafc"

export theme_primary_container="#164974"

export theme_primary_fixed="#d0e4ff"

export theme_primary_fixed_dim="#9ecafc"

export theme_scrim="#000000"

export theme_secondary="#bac8db"

export theme_secondary_container="#3b4857"

export theme_secondary_fixed="#d6e4f7"

export theme_secondary_fixed_dim="#bac8db"

export theme_shadow="#000000"

export theme_source_color="#081522"

export theme_surface="#101418"

export theme_surface_bright="#36393e"

export theme_surface_container="#1d2024"

export theme_surface_container_high="#272a2f"

export theme_surface_container_highest="#32353a"

export theme_surface_container_low="#191c20"

export theme_surface_container_lowest="#0b0e12"

export theme_surface_dim="#101418"

export theme_surface_tint="#9ecafc"

export theme_surface_variant="#42474e"

export theme_tertiary="#d5bee5"

export theme_tertiary_container="#514060"

export theme_tertiary_fixed="#f1daff"

export theme_tertiary_fixed_dim="#d5bee5"


export FZF_DEFAULT_OPTS="
    --style=full
    --color=fg:#e1e2e8,fg+:#c2c7cf
    --color=hl:#9ecafc,hl+:#d0e4ff
    --color=border:#42474e
    --color=header:#d6e4f7
    --color=gutter:#101418
    --color=spinner:#d5bee5,info:#f1daff
    --color=pointer:#d0e4ff,marker:#ffb4ab
    --color=prompt:#c2c7cf,query:#e1e2e8
    --color=preview-fg:#e1e2e8,preview-bg:-1
    --height=50%
    --layout=reverse
    --border
"
