# Generated by matugen, do not edit
export THEME_USER="#a0cafd"
export THEME_PATH="#d6bee4"
export THEME_SYMBOL="#e1e2e8"


export theme_background="#111418"

export theme_error="#ffb4ab"

export theme_error_container="#93000a"

export theme_inverse_on_surface="#2e3135"

export theme_inverse_primary="#36618e"

export theme_inverse_surface="#e1e2e8"

export theme_on_background="#e1e2e8"

export theme_on_error="#690005"

export theme_on_error_container="#ffdad6"

export theme_on_primary="#003258"

export theme_on_primary_container="#d1e4ff"

export theme_on_primary_fixed="#001d36"

export theme_on_primary_fixed_variant="#194975"

export theme_on_secondary="#253140"

export theme_on_secondary_container="#d7e3f7"

export theme_on_secondary_fixed="#101c2b"

export theme_on_secondary_fixed_variant="#3b4858"

export theme_on_surface="#e1e2e8"

export theme_on_surface_variant="#c3c7cf"

export theme_on_tertiary="#3b2948"

export theme_on_tertiary_container="#f2daff"

export theme_on_tertiary_fixed="#251431"

export theme_on_tertiary_fixed_variant="#523f5f"

export theme_outline="#8d9199"

export theme_outline_variant="#43474e"

export theme_primary="#a0cafd"

export theme_primary_container="#194975"

export theme_primary_fixed="#d1e4ff"

export theme_primary_fixed_dim="#a0cafd"

export theme_scrim="#000000"

export theme_secondary="#bbc7db"

export theme_secondary_container="#3b4858"

export theme_secondary_fixed="#d7e3f7"

export theme_secondary_fixed_dim="#bbc7db"

export theme_shadow="#000000"

export theme_source_color="#1b222b"

export theme_surface="#111418"

export theme_surface_bright="#36393e"

export theme_surface_container="#1d2024"

export theme_surface_container_high="#272a2f"

export theme_surface_container_highest="#32353a"

export theme_surface_container_low="#191c20"

export theme_surface_container_lowest="#0b0e13"

export theme_surface_dim="#111418"

export theme_surface_tint="#a0cafd"

export theme_surface_variant="#43474e"

export theme_tertiary="#d6bee4"

export theme_tertiary_container="#523f5f"

export theme_tertiary_fixed="#f2daff"

export theme_tertiary_fixed_dim="#d6bee4"


export FZF_DEFAULT_OPTS="
    --style=full
    --color=fg:#e1e2e8,fg+:#c3c7cf
    --color=hl:#a0cafd,hl+:#d1e4ff
    --color=border:#43474e
    --color=header:#d7e3f7
    --color=gutter:#111418
    --color=spinner:#d6bee4,info:#f2daff
    --color=pointer:#d1e4ff,marker:#ffb4ab
    --color=prompt:#c3c7cf,query:#e1e2e8
    --color=preview-fg:#e1e2e8,preview-bg:-1
    --height=50%
    --layout=reverse
    --border
"
